//! # forge-night: Dawn Digest Generator
//!
//! Generates the human-readable markdown report that greets the user each
//! morning after a Night Run. Fills template sections from the session and run
//! data, writes the output to `.yantra/reports/dawn_{YYYY-MM-DD}.md`, and
//! optionally delivers it to a webhook endpoint.
//!
//! ## Input
//! - `NightSession` — validated goals and decision rules from Twilight
//! - `NightReport` — completed/deferred/failed lists, cost, halt reason
//! - `DigestContext` — metrics, learnings, per-task deferral reasons
//!
//! ## Output
//! - `MarkdownReport` — rendered markdown content and its output path
//!
//! ## Related
//! - `forge-night::postmortem` — produces `DigestLearnings` consumed here
//! - `forge-night::night_run` — produces the `NightReport` consumed here

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use chrono::Utc;
use yantra_core::TaskId;

use crate::error::NightError;
use crate::night_run::{HaltReason, NightReport};
use crate::twilight::NightSession;

/// A generated Dawn Digest markdown report with its written output path.
pub struct MarkdownReport {
    /// Full rendered markdown content.
    pub content: String,
    /// Absolute path of the file written to disk.
    pub output_path: PathBuf,
}

/// Token and coverage metrics from the Night Run, all optional/zero when unavailable.
#[derive(Debug, Default)]
pub struct DigestMetrics {
    /// Total LLM tokens consumed across all tasks.
    pub total_tokens_used: u64,
    /// Number of new tests added by completed tasks.
    pub tests_added: usize,
    /// Number of tests passing in the post-run suite.
    pub tests_passing: usize,
    /// Change in code coverage (positive = improved).
    pub coverage_delta_pct: Option<f32>,
    /// Change in clean-build time in milliseconds (negative = faster).
    pub build_time_delta_ms: Option<i64>,
}

/// A single skill entry modified during the Night Run.
pub struct SkillUpdate {
    /// SKILL.md file name without extension.
    pub name: String,
    /// Whether this entry was created fresh or updated in place.
    pub action: SkillAction,
}

/// Whether a SKILL.md was written for the first time or updated.
pub enum SkillAction {
    /// Brand-new skill file was written.
    Added,
    /// Existing skill file was modified.
    Updated,
}

/// Summary of new learnings generated by the Postmortem phase.
#[derive(Default)]
pub struct DigestLearnings {
    /// Skill files written or updated during the session.
    pub skills_updated: Vec<SkillUpdate>,
    /// Number of new entries added to the Mistake Library.
    pub mistake_records_added: usize,
}

/// Auxiliary data supplied alongside the `NightReport` for rich digest sections.
#[derive(Default)]
pub struct DigestContext {
    /// Quantitative metrics from the Night Run.
    pub metrics: DigestMetrics,
    /// Learnings extracted by the Postmortem.
    pub learnings: DigestLearnings,
    /// Per-task reason a task was deferred, keyed by task ID.
    pub deferred_task_reasons: HashMap<TaskId, String>,
    /// Redacted one-line security summaries for halted tasks.
    pub halted_security_summaries: Vec<String>,
}

/// Generates the Dawn Digest, writes it to `.yantra/reports/dawn_{date}.md`,
/// and returns the report for optional webhook delivery.
///
/// # Errors
///
/// Returns `NightError::DigestIo` when the reports directory or the output
/// file cannot be created or written.
pub fn generate_digest(
    session: &NightSession,
    report: &NightReport,
    context: &DigestContext,
    yantra_dir: &Path,
) -> Result<MarkdownReport, NightError> {
    let date_string = Utc::now().format("%Y-%m-%d").to_string();
    let digest_markdown = render_digest(session, report, context, &date_string);

    let output_path = yantra_dir
        .join("reports")
        .join(format!("dawn_{date_string}.md"));

    if let Some(parent_directory) = output_path.parent() {
        std::fs::create_dir_all(parent_directory).map_err(|io_error| NightError::DigestIo {
            path: parent_directory.display().to_string(),
            reason: io_error.to_string(),
        })?;
    }

    std::fs::write(&output_path, &digest_markdown).map_err(|io_error| NightError::DigestIo {
        path: output_path.display().to_string(),
        reason: io_error.to_string(),
    })?;

    Ok(MarkdownReport {
        content: digest_markdown,
        output_path,
    })
}

/// Delivers the digest markdown to a webhook via HTTP POST.
///
/// # Errors
///
/// Returns `NightError::WebhookDeliveryFailed` on network or HTTP failure.
pub async fn notify_webhook(webhook_url: &str, report: &MarkdownReport) -> Result<(), NightError> {
    let http_client = reqwest::Client::new();
    let response = http_client
        .post(webhook_url)
        .header("Content-Type", "text/markdown; charset=utf-8")
        .body(report.content.clone())
        .send()
        .await
        .map_err(|request_error| NightError::WebhookDeliveryFailed(request_error.to_string()))?;

    if !response.status().is_success() {
        return Err(NightError::WebhookDeliveryFailed(format!(
            "HTTP {} from webhook endpoint",
            response.status()
        )));
    }

    Ok(())
}

fn render_digest(
    session: &NightSession,
    report: &NightReport,
    context: &DigestContext,
    date_string: &str,
) -> String {
    let duration_mins = report.run_duration.as_secs() / 60;
    let duration_secs = report.run_duration.as_secs() % 60;
    let halt_description = halt_reason_to_description(&report.halt_reason);

    let mut markdown = format!(
        "# Dawn Digest — {date_string}\n\n\
        **Session:** `{session_id}`  \n\
        **Halt reason:** {halt_description}  \n\
        **Duration:** {duration_mins}m {duration_secs}s  \n\
        **Total cost:** ${cost:.4} USD\n\n",
        session_id = report.session_id,
        cost = report.total_cost_usd,
    );

    markdown.push_str(&render_completed_section(report, session));
    markdown.push_str(&render_deferred_section(report, session, context));
    markdown.push_str(&render_halted_section(report, session, context));
    markdown.push_str(&render_metrics_section(report, context));
    markdown.push_str(&render_learnings_section(context));

    markdown
}

fn halt_reason_to_description(halt_reason: &HaltReason) -> String {
    match halt_reason {
        HaltReason::AllTasksComplete => "All tasks completed successfully.".to_owned(),
        HaltReason::BudgetExceeded { total_usd } => {
            format!("Budget cap exceeded at ${total_usd:.4} USD.")
        }
        HaltReason::CircuitOpen => "Circuit breaker opened — LLM rate limit hit.".to_owned(),
        HaltReason::WatchdogDead => "Watchdog channel closed unexpectedly.".to_owned(),
        HaltReason::HardStop { notify } => format!(
            "Hard stop triggered{}.",
            if *notify { " (user notified)" } else { "" }
        ),
    }
}

fn render_completed_section(report: &NightReport, session: &NightSession) -> String {
    let count = report.completed_task_ids.len();
    let mut section = format!("## ✅ Completed ({count})\n\n");

    if count == 0 {
        section.push_str("_No tasks completed in this session._\n\n");
        return section;
    }

    for task_id in &report.completed_task_ids {
        let description = session
            .validated_goals
            .iter()
            .find(|goal| goal.source_truth.task_id == *task_id)
            .map_or("(unknown task)", |goal| goal.spec.description.as_str());

        let task_id_short = &task_id.to_string()[..8];
        section.push_str(&format!(
            "- **`{task_id}`** — {description}  \n  \
             _Branch:_ `night/.../{task_id_short}` | \
             _Decision trail:_ `archaeology/{task_id}.json`\n",
        ));
    }

    section.push('\n');
    section
}

fn render_deferred_section(
    report: &NightReport,
    session: &NightSession,
    context: &DigestContext,
) -> String {
    let count = report.deferred_task_ids.len();
    let mut section = format!("## ⚠️ Deferred ({count})\n\n");

    if count == 0 {
        section.push_str("_No tasks deferred in this session._\n\n");
        return section;
    }

    for task_id in &report.deferred_task_ids {
        let description = session
            .validated_goals
            .iter()
            .find(|goal| goal.source_truth.task_id == *task_id)
            .map_or("(unknown task)", |goal| goal.spec.description.as_str());

        let reason = context
            .deferred_task_reasons
            .get(task_id)
            .map_or("Policy decision or low confidence score", String::as_str);

        section.push_str(&format!(
            "- **`{task_id}`** — {description}  \n  \
             _Reason:_ {reason} | _Questions:_ `questions/{task_id}.md`\n",
        ));
    }

    section.push('\n');
    section
}

fn render_halted_section(
    report: &NightReport,
    session: &NightSession,
    context: &DigestContext,
) -> String {
    let failed_count = report.failed_task_ids.len();
    let security_count = context.halted_security_summaries.len();
    let total = failed_count + security_count;
    let mut section = format!("## 🚨 Halted ({total})\n\n");

    if total == 0 {
        section.push_str("_No tasks halted in this session._\n\n");
        return section;
    }

    for task_id in &report.failed_task_ids {
        let description = session
            .validated_goals
            .iter()
            .find(|goal| goal.source_truth.task_id == *task_id)
            .map_or("(unknown task)", |goal| goal.spec.description.as_str());

        section.push_str(&format!(
            "- **`{task_id}`** — {description}: _permanent failure_\n"
        ));
    }

    for (security_index, security_summary) in context.halted_security_summaries.iter().enumerate() {
        let redacted = redact_sensitive_content(security_summary);
        section.push_str(&format!(
            "- **Security event #{security_index}** — {redacted}\n"
        ));
    }

    section.push('\n');
    section
}

fn render_metrics_section(report: &NightReport, context: &DigestContext) -> String {
    let duration_mins = report.run_duration.as_secs() / 60;
    let duration_secs = report.run_duration.as_secs() % 60;

    let coverage_cell = context
        .metrics
        .coverage_delta_pct
        .map_or_else(|| "n/a".to_owned(), |delta| format!("{delta:+.1}%"));
    let build_time_cell = context
        .metrics
        .build_time_delta_ms
        .map_or_else(|| "n/a".to_owned(), |delta| format!("{delta:+}ms"));

    format!(
        "## 📊 Metrics\n\n\
        | Metric           | Value |\n\
        |------------------|-------|\n\
        | Cost             | ${cost:.4} USD |\n\
        | Tokens used      | {tokens} |\n\
        | Duration         | {duration_mins}m {duration_secs}s |\n\
        | Tests added      | {tests_added} |\n\
        | Tests passing    | {tests_passing} |\n\
        | Coverage delta   | {coverage_cell} |\n\
        | Build time delta | {build_time_cell} |\n\n",
        cost = report.total_cost_usd,
        tokens = context.metrics.total_tokens_used,
        tests_added = context.metrics.tests_added,
        tests_passing = context.metrics.tests_passing,
    )
}

fn render_learnings_section(context: &DigestContext) -> String {
    let mut section = "## 🧠 What I Learned\n\n".to_owned();

    let has_skills = !context.learnings.skills_updated.is_empty();
    let has_mistakes = context.learnings.mistake_records_added > 0;

    if !has_skills && !has_mistakes {
        section.push_str("_No new skills or Mistake Library entries generated this session._\n\n");
        return section;
    }

    if has_skills {
        section.push_str("**Skills:**\n\n");
        for skill_update in &context.learnings.skills_updated {
            let action_label = match skill_update.action {
                SkillAction::Added => "added",
                SkillAction::Updated => "updated",
            };
            section.push_str(&format!("- `{}` ({action_label})\n", skill_update.name));
        }
        section.push('\n');
    }

    if has_mistakes {
        let plural = if context.learnings.mistake_records_added == 1 {
            "y"
        } else {
            "ies"
        };
        section.push_str(&format!(
            "**Mistake Library:** {} new entr{plural} added — prevention rules injected into future task contexts.\n\n",
            context.learnings.mistake_records_added,
        ));
    }

    section
}

/// Replaces long opaque token-like strings (>20 alphanumeric chars) with `[REDACTED]`.
fn redact_sensitive_content(text: &str) -> String {
    text.split_whitespace()
        .map(|word| {
            let stripped = word.trim_matches(|character: char| !character.is_alphanumeric());
            if stripped.len() > 20
                && stripped.chars().all(|character| {
                    character.is_ascii_alphanumeric()
                        || character == '+'
                        || character == '/'
                        || character == '='
                })
            {
                word.replace(stripped, "[REDACTED]")
            } else {
                word.to_owned()
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;
    use std::time::Duration;

    use chrono::Utc;
    use yantra_core::{DecisionId, SessionId, Strictness, TaskClass, TaskId};
    use yantra_stvp::{issue_token, SigningKey, SourceTruth};

    use super::*;
    use crate::decision_rules::DecisionRule;
    use crate::mode_policy::TRUST_POLICY;
    use crate::night_run::TaskDisposition;
    use crate::twilight::{NightSession, TaskSpec, ValidatedGoal};

    fn temp_yantra_dir() -> PathBuf {
        let root = std::env::temp_dir().join(format!("yantra-digest-{}", TaskId::new()));
        std::fs::create_dir_all(&root).unwrap();
        root
    }

    fn fixture_session(yantra_dir: &Path) -> (NightSession, TaskId) {
        let signing_key = SigningKey::load_or_generate(yantra_dir).unwrap();
        let task_id = TaskId::new();
        let source_truth = SourceTruth {
            task_id,
            task_class: TaskClass::NewFeature,
            strictness: Strictness::Trust,
            description: "add authentication middleware".to_owned(),
            created_at: Utc::now(),
            answers: BTreeMap::new(),
            augmented_question_ids: Vec::new(),
        };
        let truth_token = issue_token(&source_truth, &signing_key).unwrap();
        let session = NightSession {
            session_id: SessionId::new(),
            validated_goals: vec![ValidatedGoal {
                spec: TaskSpec::new("add authentication middleware"),
                source_truth,
                truth_token,
            }],
            decision_rules: Vec::<DecisionRule>::new(),
            policy: TRUST_POLICY,
            night_plan_markdown: "# Plan\n".to_owned(),
        };
        (session, task_id)
    }

    fn fixture_report(session_id: SessionId, completed_task_ids: Vec<TaskId>) -> NightReport {
        NightReport {
            session_id,
            completed_task_ids,
            deferred_task_ids: Vec::new(),
            failed_task_ids: Vec::new(),
            total_cost_usd: 0.05,
            run_duration: Duration::from_secs(300),
            dawn_digest_markdown: String::new(),
            halt_reason: HaltReason::AllTasksComplete,
            task_retry_counts: std::collections::HashMap::new(),
        }
    }

    #[test]
    fn digest_template_produces_expected_markdown_for_fixture_session() {
        let yantra_dir = temp_yantra_dir();
        let (session, task_id) = fixture_session(&yantra_dir);
        let report = fixture_report(session.session_id, vec![task_id]);
        let context = DigestContext::default();

        let digest = generate_digest(&session, &report, &context, &yantra_dir).unwrap();

        assert!(digest.content.contains("Dawn Digest"), "must contain title");
        assert!(
            digest.content.contains("✅ Completed (1)"),
            "must show completed count"
        );
        assert!(
            digest.content.contains("⚠️ Deferred (0)"),
            "must show deferred count"
        );
        assert!(
            digest.content.contains("📊 Metrics"),
            "must contain metrics section"
        );
        assert!(
            digest.content.contains("🧠 What I Learned"),
            "must contain learnings section"
        );
        assert!(
            digest.content.contains("add authentication middleware"),
            "must include task description"
        );
        assert!(
            digest.output_path.exists(),
            "output file must exist on disk"
        );
    }

    #[test]
    fn digest_includes_per_task_deferral_reasons() {
        let yantra_dir = temp_yantra_dir();
        let (session, task_id) = fixture_session(&yantra_dir);
        let mut report = fixture_report(session.session_id, Vec::new());
        report.deferred_task_ids.push(task_id);

        let mut context = DigestContext::default();
        context
            .deferred_task_reasons
            .insert(task_id, "low confidence score: 0.42".to_owned());

        let digest = generate_digest(&session, &report, &context, &yantra_dir).unwrap();
        assert!(
            digest.content.contains("low confidence score: 0.42"),
            "deferral reason must appear in digest"
        );
    }

    #[test]
    fn digest_includes_skill_and_mistake_learnings() {
        let yantra_dir = temp_yantra_dir();
        let (session, task_id) = fixture_session(&yantra_dir);
        let report = fixture_report(session.session_id, vec![task_id]);

        let mut context = DigestContext::default();
        context.learnings.skills_updated.push(SkillUpdate {
            name: "rust-async-retry".to_owned(),
            action: SkillAction::Added,
        });
        context.learnings.mistake_records_added = 2;

        let digest = generate_digest(&session, &report, &context, &yantra_dir).unwrap();
        assert!(digest.content.contains("rust-async-retry"));
        assert!(digest.content.contains("2 new entries added"));
    }

    #[test]
    fn redact_sensitive_content_replaces_long_token_strings() {
        let input = "error: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9abcdefgh rejected by server";
        let redacted = redact_sensitive_content(input);
        assert!(
            redacted.contains("[REDACTED]"),
            "long token must be redacted"
        );
        assert!(
            !redacted.contains("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9abcdefgh"),
            "original token must not appear"
        );
        assert!(
            redacted.contains("error:"),
            "non-sensitive words must survive"
        );
    }

    #[test]
    fn digest_section_for_halted_tasks_shows_redacted_security_event() {
        let yantra_dir = temp_yantra_dir();
        let (session, _) = fixture_session(&yantra_dir);
        let report = fixture_report(session.session_id, Vec::new());

        let mut context = DigestContext::default();
        context
            .halted_security_summaries
            .push("credential leak: token AAABBBCCCDDDEEEFFFGGG found in diff".to_owned());

        let digest = generate_digest(&session, &report, &context, &yantra_dir).unwrap();
        assert!(
            digest.content.contains("Security event #0"),
            "security event header must appear"
        );
        assert!(
            !digest.content.contains("AAABBBCCCDDDEEEFFFGGG"),
            "raw token must be redacted"
        );
    }

    // Silence unused import warning from fixture_report using TaskDisposition
    #[allow(dead_code)]
    fn _uses_task_disposition() -> TaskDisposition {
        TaskDisposition::Completed
    }

    // Silence unused import for DecisionId
    #[allow(dead_code)]
    fn _uses_decision_id() -> DecisionId {
        DecisionId::new()
    }
}
